"""Reporting exports for pyqicharts.

PNG export uses matplotlib, which is already part of the core package. Excel
and PowerPoint export libraries are imported lazily so the core install stays
lightweight until users ask for reporting features.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Iterable

import pandas as pd


def _as_chart_list(charts_or_chart) -> list:
    """Accept either one chart or a list/tuple of charts."""
    if isinstance(charts_or_chart, (list, tuple)):
        return list(charts_or_chart)
    return [charts_or_chart]


def _missing_optional(package: str, extra: str = "reporting") -> ImportError:
    """Build a consistent optional-dependency error message."""
    return ImportError(
        f"{package} is required for this export. Install it with "
        f"`pip install pyqicharts[{extra}]` or install {package!r} directly."
    )


def export_png(chart, path: str | Path, dpi: int = 150) -> Path:
    """Save a chart figure as a PNG file and return the output path."""

    output = Path(path)
    output.parent.mkdir(parents=True, exist_ok=True)
    chart.figure.savefig(output, dpi=dpi, bbox_inches="tight")
    return output


def export_excel(chart, path: str | Path, include_image: bool = True) -> Path:
    """Export chart data and SPC summaries to an Excel workbook."""

    # Optional import boundary: users can still import pyqicharts without
    # openpyxl installed, and only see this error when Excel export is used.
    try:
        from openpyxl import Workbook
        from openpyxl.drawing.image import Image as ExcelImage
        from openpyxl.utils.dataframe import dataframe_to_rows
    except ImportError as exc:
        raise _missing_optional("openpyxl") from exc

    from .powerbi import special_cause_summary_table, spc_summary_table

    charts = _as_chart_list(chart)
    output = Path(path)
    output.parent.mkdir(parents=True, exist_ok=True)
    workbook = Workbook()
    workbook.remove(workbook.active)

    for index, chart_item in enumerate(charts, start=1):
        suffix = "" if len(charts) == 1 else f" {index}"
        data_sheet = workbook.create_sheet(f"Chart data{suffix}")
        for row in dataframe_to_rows(chart_item.table, index=False, header=True):
            data_sheet.append(row)

        summary_sheet = workbook.create_sheet(f"SPC summary{suffix}")
        for row in dataframe_to_rows(spc_summary_table(chart_item), index=False, header=True):
            summary_sheet.append(row)

        signals_sheet = workbook.create_sheet(f"Special causes{suffix}")
        for row in dataframe_to_rows(special_cause_summary_table(chart_item), index=False, header=True):
            signals_sheet.append(row)

    if include_image:
        for index, chart_item in enumerate(charts, start=1):
            suffix = "" if len(charts) == 1 else f" {index}"
            image_path = output.with_name(f"{output.stem}_{index}.png")
            export_png(chart_item, image_path)
            image_sheet = workbook.create_sheet(f"Chart image{suffix}")
            image_sheet.add_image(ExcelImage(str(image_path)), "A1")

    workbook.save(output)
    return output


def export_powerpoint(chart, path: str | Path, title: str | None = None, summary_text: str | None = None) -> Path:
    """Export one or more charts to a simple PowerPoint deck."""

    # Optional import boundary for PowerPoint reporting.
    try:
        from pptx import Presentation
        from pptx.util import Inches, Pt
    except ImportError as exc:
        raise _missing_optional("python-pptx") from exc

    charts = _as_chart_list(chart)
    output = Path(path)
    output.parent.mkdir(parents=True, exist_ok=True)

    presentation = Presentation()
    title_slide = presentation.slides.add_slide(presentation.slide_layouts[0])
    title_slide.shapes.title.text = title or "pyqicharts report"
    title_slide.placeholders[1].text = summary_text or "Generated by pyqicharts"

    for index, chart_item in enumerate(charts, start=1):
        image_path = output.with_name(f"{output.stem}_{index}.png")
        export_png(chart_item, image_path)
        slide = presentation.slides.add_slide(presentation.slide_layouts[5])
        slide.shapes.title.text = f"{chart_item.chart.upper()} chart of {chart_item.y}"
        slide.shapes.add_picture(str(image_path), Inches(0.6), Inches(1.1), width=Inches(8.8))

        textbox = slide.shapes.add_textbox(Inches(0.7), Inches(6.4), Inches(8.6), Inches(0.4))
        frame = textbox.text_frame
        frame.text = summary_text or f"Signals detected: {int(chart_item.signals.sum())}"
        frame.paragraphs[0].font.size = Pt(12)

    presentation.save(output)
    return output


def create_report_bundle(charts: Iterable, output_dir: str | Path) -> dict:
    """Create PNG, Excel, PowerPoint and metadata outputs for charts."""

    folder = Path(output_dir)
    folder.mkdir(parents=True, exist_ok=True)
    charts = list(charts)
    png_files = []
    for index, chart in enumerate(charts, start=1):
        png_files.append(str(export_png(chart, folder / f"chart_{index}.png")))

    excel_file = str(export_excel(charts, folder / "report.xlsx")) if charts else ""
    pptx_file = str(export_powerpoint(charts, folder / "report.pptx")) if charts else ""
    # Metadata gives automation/reporting workflows a simple manifest of files
    # created by the bundle.
    metadata = {
        "chart_count": len(charts),
        "png_files": png_files,
        "excel_file": excel_file,
        "powerpoint_file": pptx_file,
    }
    metadata_path = folder / "metadata.json"
    metadata_path.write_text(json.dumps(metadata, indent=2), encoding="utf-8")
    metadata["metadata_file"] = str(metadata_path)
    return metadata
